_core:
  default_config_hash: 7Ml-sDtRf3JRL4NJLwt_twa-rdBi4hFnwPSd2vb1_JA
api_key: ''
domain: plexii.org
use_oauth: true
api_timeout: 10
cron: false
batch_limit: 100
api_classname: Mailchimp\Mailchimp
test_mode: false
optin_check_email_msg: 'Please check your email to confirm your subscription.'
